language: php

php:
  - 7.1

install:
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer install --dev

script: 
  - cd test
  - ./../vendor/bin/codecept build
  - ./../vendor/bin/codecept run --coverage
